import {
  BadgeCheck,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarClock,
  ClipboardList,
  FileText,
  FileUp,
  GraduationCap,
  HeartHandshake,
  LayoutDashboard,
  Layers,
  Library,
  Megaphone,
  MessageSquare,
  NotebookPen,
  HeartPulse,
  Receipt,
  Settings,
  ShieldCheck,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/** Icons the sidebar can show, looked up by name (see NavItem.icon). */
export const NAV_ICONS = {
  BadgeCheck,
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarClock,
  ClipboardList,
  FileText,
  FileUp,
  GraduationCap,
  HeartHandshake,
  LayoutDashboard,
  Layers,
  Library,
  Megaphone,
  MessageSquare,
  NotebookPen,
  HeartPulse,
  Receipt,
  Settings,
  ShieldCheck,
  Users,
  Wallet,
} satisfies Record<string, LucideIcon>;

export type NavIconName = keyof typeof NAV_ICONS;
